[window]
opacity = 0.8
decorations = "None"
dimensions = { columns = 80, lines =  24}

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen"},
{ key = "Q", mods = "Control", action = "Quit"},
{ key = "V", mods = "Control", action = "Paste"},
{ key = "C", mods = "Control", action = "Copy"},
{ key = "T", mods = "Control", action = "CreateNewWindow"}
]

[font]
size = 9.50

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#fa4869"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#0d0c0c"
foreground = "#a9b1d6"