#!/bin/sh

# Terminate already running instances
pkill -x sxhkd

# Start sxhkd
sxhkd &

# Set wallpaper
nitrogen --restore &

# Set panel (polybar example)
polybar example &

# Start compositor
picom &

dunst & 

# Configure bspwm behavior
bspc monitor -d 1 2 3 4 5

# detect full screen
bspc subscribe node | while read -r event; do
    if [[ "$event" =~ "fullscreen" ]]; then
        HideBar
    fi
    if [[ "$event" =~ "unfullscreen" ]]; then
        ShowBar
    fi
done

