#!/usr/bin/env zsh

# Notification command
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obvolume'

# Get Volume
get_volume() {
	pamixer --get-volume-human | sed 's/%//'
}

# Increase Volume
inc_volume() {
	[[ $(pamixer --get-mute) == true ]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -i 5 
}

# Decrease Volume
dec_volume() {
	[[ $(pamixer --get-mute) == true ]] && pamixer -u
	pamixer --allow-boost --set-limit 150 -d 5 
}

# Toggle Mute
toggle_mute() {
	if [[ $(pamixer --get-mute) == false ]]; then
		pamixer --toggle-mute
	else
		pamixer --toggle-mute 
	fi
}

# Execute accordingly
if [[ -x $(which pamixer) ]]; then
	if [[ "$1" == "--get" ]]; then
		get_volume
	elif [[ "$1" == "--inc" ]]; then
		inc_volume
	elif [[ "$1" == "--dec" ]]; then
		dec_volume
	elif [[ "$1" == "--toggle" ]]; then
		toggle_mute
	else
		echo "$(get_volume)%"
	fi
else
	${notify_cmd} "'pamixer' is not installed."
fi